
import Head from "next/head";
import "./globals.css";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AmazonClone",
  description: "Generated by Nextjs 13",
  icons:{
    icon:'/icon.ico?v=4',
    apple:'/icon.ico?v=4'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by Nextjs 13" />
       
      </Head>

      <body className={`${inter.className} bg-gray-200`}>
       
        {/* <HomeCategoryCard /> */}
        {children}
      </body>
    </html>
  );
}
