const ProductList = [
  {
    id: "1",
    name: "Product 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: 29.99,
    image: "product1.jpg",
    category: "Electronics",
    rating: 4.5,
    reviews: 10,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product1",
  },
  {
    id: "2",
    name: "Product 2",
    description:
      "Nullam lobortis neque ut est commodo, in vulputate lacus dignissim.",
    price: 39.99,
    image: "product2.jpg",
    category: "Fashion",
    rating: 4.2,
    reviews: 8,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product2",
  },
  {
    id: "3",
    name: "Product 3",
    description: "Sed euismod mi id quam aliquam, a rhoncus felis eleifend.",
    price: 49.99,
    image: "product3.jpg",
    category: "Home",
    rating: 4.8,
    reviews: 12,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product3",
  },
  {
    id: "4",
    name: "Product 4",
    description: "Maecenas nec est consectetur, lacinia mi at, mattis nulla.",
    price: 19.99,
    image: "product4.jpg",
    category: "Beauty",
    rating: 4.6,
    reviews: 15,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product4",
  },
  {
    id: "5",
    name: "Product 5",
    description:
      "Fusce in odio consectetur, scelerisque justo nec, ullamcorper urna.",
    price: 34.99,
    image: "product5.jpg",
    category: "Electronics",
    rating: 4.4,
    reviews: 7,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product5",
  },
  {
    id: "6",
    name: "Product 6",
    description:
      "Pellentesque vitae est luctus, venenatis ex non, ullamcorper arcu.",
    price: 59.99,
    image: "product6.jpg",
    category: "Fashion",
    rating: 4.7,
    reviews: 9,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product6",
  },
  {
    id: "7",
    name: "Product 7",
    description: "Vestibulum at nunc vitae diam sagittis dapibus vel ut est.",
    price: 44.99,
    image: "product7.jpg",
    category: "Home",
    rating: 4.3,
    reviews: 11,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product7",
  },
  {
    id: "8",
    name: "Product 8",
    description: "Curabitur ac ex in est dictum commodo non at turpis.",
    price: 24.99,
    image: "product8.jpg",
    category: "Beauty",
    rating: 4.9,
    reviews: 13,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product8",
  },
  {
    id: "9",
    name: "Product 9",
    description:
      "Nam ullamcorper urna ut luctus tempor. Etiam auctor sodales ipsum.",
    price: 27.99,
    image: "product9.jpg",
    category: "Electronics",
    rating: 4.1,
    reviews: 6,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product9",
  },
  {
    id: "10",
    name: "Product 10",
    description:
      "Praesent eleifend nisi vel commodo tempor. Ut consectetur metus.",
    price: 37.99,
    image: "product10.jpg",
    category: "Fashion",
    rating: 4.7,
    reviews: 10,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product10",
  },
  {
    id: "11",
    name: "Product 11",
    description:
      "Sed bibendum lorem eget mauris laoreet, et consequat sapien volutpat.",
    price: 64.99,
    image: "product11.jpg",
    category: "Home",
    rating: 4.6,
    reviews: 12,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product11",
  },
  {
    id: "12",
    name: "Product 12",
    description: "Duis id urna sit amet tortor luctus congue a eget leo.",
    price: 19.99,
    image: "product12.jpg",
    category: "Beauty",
    rating: 4.3,
    reviews: 8,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product12",
  },
  {
    id: "13",
    name: "Product 13",
    description: "Vestibulum a justo id libero faucibus interdum at id justo.",
    price: 39.99,
    image: "product13.jpg",
    category: "Electronics",
    rating: 4.8,
    reviews: 15,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product13",
  },
  {
    id: "14",
    name: "Product 14",
    description:
      "Donec sagittis neque eget mauris luctus, eget tristique quam fringilla.",
    price: 29.99,
    image: "product14.jpg",
    category: "Fashion",
    rating: 4.2,
    reviews: 7,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product14",
  },
  {
    id: "15",
    name: "Product 15",
    description:
      "Aenean suscipit justo vel enim facilisis, in maximus ex varius.",
    price: 49.99,
    image: "product15.jpg",
    category: "Home",
    rating: 4.5,
    reviews: 9,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product15",
  },
  {
    id: "16",
    name: "Product 16",
    description:
      "Morbi cursus lacus in lectus elementum, non mattis sapien viverra.",
    price: 24.99,
    image: "product16.jpg",
    category: "Beauty",
    rating: 4.9,
    reviews: 11,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product16",
  },
  {
    id: "17",
    name: "Product 17",
    description:
      "Quisque placerat elit ac velit lacinia, nec pharetra turpis malesuada.",
    price: 34.99,
    image: "product17.jpg",
    category: "Electronics",
    rating: 4.4,
    reviews: 10,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product17",
  },
  {
    id: "18",
    name: "Product 18",
    description:
      "Nunc euismod nulla ut metus vulputate, id ultricies odio tristique.",
    price: 59.99,
    image: "product18.jpg",
    category: "Fashion",
    rating: 4.7,
    reviews: 14,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product18",
  },
  {
    id: "19",
    name: "Product 19",
    description:
      "Pellentesque ac ligula eu nulla semper consectetur sit amet eget odio.",
    price: 44.99,
    image: "product19.jpg",
    category: "Home",
    rating: 4.3,
    reviews: 9,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product19",
  },
  {
    id: "20",
    name: "Product 20",
    description:
      "Proin accumsan lacus eu nisl dignissim, ac aliquet est lobortis.",
    price: 27.99,
    image: "product20.jpg",
    category: "Beauty",
    rating: 4.6,
    reviews: 12,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product20",
  },
];
export default ProductList;
