const ProductList = [
  {
    id: "1",
    name: "Camera Stand",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: 29.99,
    image: "./products/cameraStand.jpeg",
    category: "Electronics",
    rating: 4.5,
    reviews: 10,
    discountedPrice: 50,
    offer: 0,
    linkTitle: "View Product",
    link: "/product1",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "2",
    name: "Powerjs Tower",
    description:
      "Nullam lobortis neque ut est commodo, in vulputate lacus dignissim.",
    price: 39.99,
    image: " ./products/Powerjstower.jpeg",
    category: "Fashion",
    rating: 4.2,
    reviews: 8,
    discountedPrice: 30,
    offer: 0,
    linkTitle: "View Product",
    link: "/product2",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "3",
    name: "Product 3",
    description: "Sed euismod mi id quam aliquam, a rhoncus felis eleifend.",
    price: 49.99,
    image: "./products/videoDoorbell.jpeg",
    category: "Home",
    rating: 4.8,
    reviews: 12,
    discountedPrice: 20,
    offer: 0,
    linkTitle: "View Product",
    link: "/product3",

    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "4",
    name: "Blue Shirt",
    description: "Maecenas nec est consectetur, lacinia mi at, mattis nulla.",
    price: 19.99,
    image: "./products/blueShirt.jpeg",
    category: "boy",
    rating: 4.6,
    reviews: 15,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/blueShirt",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "5",
    name: "Black T-Shirt",
    description:
      "Fusce in odio consectetur, scelerisque justo nec, ullamcorper urna.",
    price: 34.99,
    image: "./products/blackTshirt.jpeg",
    category: "boys",
    rating: 4.4,
    reviews: 7,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/blackTshirt",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "6",
    name: "Magnesium Capsule",
    description:
      "Pellentesque vitae est luctus, venenatis ex non, ullamcorper arcu.",
    price: 59.99,
    image: "./products/magnesium.jpeg",
    category: "Fashion",
    rating: 4.7,
    reviews: 9,
    discountedPrice: 60,
    offer: 0,
    linkTitle: "View Product",
    link: "/magnesium",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "7",
    name: "Product 7",
    description: "Vestibulum at nunc vitae diam sagittis dapibus vel ut est.",
    price: 44.99,
    image: "./products/videoDoorbell.jpeg",
    category: "Home",
    rating: 4.3,
    reviews: 11,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product7",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "8",
    name: "Product 8",
    description: "Curabitur ac ex in est dictum commodo non at turpis.",
    price: 24.99,
    image: "./products/videoDoorbell.jpeg",
    category: "Beauty",
    rating: 4.9,
    reviews: 13,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product8",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "9",
    name: "Oral Toothbrush",
    description:
      "Nam ullamcorper urna ut luctus tempor. Etiam auctor sodales ipsum.",
    price: 27.99,
    image: " ./products/toothbrush.jpeg",
    category: "Electronics",
    rating: 4.1,
    reviews: 6,
    discountedPrice: 5,
    offer: 0,
    linkTitle: "View Product",
    link: "/toothbrush",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "10",
    name: "Video Door Bell",
    description:
      "Praesent eleifend nisi vel commodo tempor. Ut consectetur metus.",
    price: 37.99,
    image: "./products/videoDoorbell.jpeg",
    category: "Fashion",
    rating: 4.7,
    reviews: 10,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/product10",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "11",
    name: "Timtam Biscuite",
    description:
      "Sed bibendum lorem eget mauris laoreet, et consequat sapien volutpat.",
    price: 64.99,
    image: "./products/timtambiscuite.jpeg",
    category: "Home",
    rating: 4.6,
    reviews: 12,
    discountedPrice: 0,
    offer: 0,
    linkTitle: "View Product",
    link: "/timtambiscuite",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "12",
    name: "Chocolate",
    description: "Duis id urna sit amet tortor luctus congue a eget leo.",
    price: 19.99,
    image: "./products/chocolate.jpeg",
    category: "Beauty",
    rating: 4.3,
    reviews: 8,
    discountedPrice: 0,
    earlyPrimeDeal: true,
    linkTitle: "View Product",
    link: "/chcolate",
    totalPurchase: 12340,
    trending: true,
  },
  {
    id: "13",
    name: "Coconut Water",
    description: "Vestibulum a justo id libero faucibus interdum at id justo.",
    price: 39.99,
    image: "./products/coconutwater.jpeg",
    category: "Drinks",
    rating: 4.8,
    reviews: 15,
    discountedPrice: 0,
    freePrimeDeal: true,
    linkTitle: "View Product",
    link: "/coocnutwater",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "14",
    name: "Bath Towel",
    description:
      "Donec sagittis neque eget mauris luctus, eget tristique quam fringilla.",
    price: 29.99,
    image: "./products/bathtowel.jpeg",
    category: "Fashion",
    rating: 4.2,
    reviews: 7,
    discountedPrice: 0,
    freePrimeDeal: true,
    linkTitle: "View Product",
    link: "/product14",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "15",
    name: "MacBook Pro M2 13 inches",
    description:
      "Aenean suscipit justo vel enim facilisis, in maximus ex varius.",
    price: 49.99,
    image: "./products/macbookProM2-13.jpeg",
    category: "electronics",
    rating: 4.5,
    reviews: 9,
    discountedPrice: 0,
    freePrimeDeal: true,
    linkTitle: "View Product",
    link: "/macbookProM2-13",
    totalPurchase: 1234,
    trending: true,
  },
  {
    id: "16",
    name: "SuitCase",
    description:
      "Morbi cursus lacus in lectus elementum, non mattis sapien viverra.",
    price: 24.99,
    image: "./products/Suitcase.jpeg",
    category: "Beauty",
    rating: 4.9,
    reviews: 11,
    discountedPrice: 0,
    freePrimeDeal: true,
    linkTitle: "View Product",
    link: "/product16",
    totalPurchase: 1234,
    trending: true,
  },
  {
    id: "17",
    name: "Remoter Controller",
    description:
      "Quisque placerat elit ac velit lacinia, nec pharetra turpis malesuada.",
    price: 34.99,
    image: "./products/remoteController.jpeg",
    category: "Electronics",
    rating: 4.4,
    reviews: 10,
    discountedPrice: 70,
    offer: 0,
    earlyPrimeDeal: true,
    linkTitle: "View Product",
    link: "/product17",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "18",
    name: "Eco Dots",
    description:
      "Nunc euismod nulla ut metus vulputate, id ultricies odio tristique.",
    price: 59.99,
    image: "./products/ecoDot.jpeg",
    category: "Fashion",
    rating: 4.7,
    reviews: 14,
    discountedPrice: 60,
    offer: 0,
    earlyPrimeDeal: true,
    linkTitle: "View Product",
    link: "/product18",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "19",
    name: "Kindle Scribe",
    description:
      "Pellentesque ac ligula eu nulla semper consectetur sit amet eget odio.",
    price: 44.99,
    image: "./products/kindleScribe.jpeg",
    category: "Home",
    rating: 4.3,
    reviews: 9,
    discountedPrice: 50,
    offer: 0,
    earlyPrimeDeal: true,
    linkTitle: "View Product",
    link: "/product19",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "20",
    name: "HP Intel i7 13 inches",
    description:
      "Proin accumsan lacus eu nisl dignissim, ac aliquet est lobortis.",
    price: 2000.99,
    image: "./products/hp13inches.jpeg",
    category: "Beauty",
    rating: 4.6,
    reviews: 12,
    discountedPrice: 40,
    offer: 0,
    earlyPrimeDeal: true,
    linkTitle: "View Product",
    link: "/hp13inches",
    totalPurchase: 1234,
    trending: false,
  },
  ,
  {
    id: "21",
    name: "Cube TV Speaker",
    description:
      "Proin accumsan lacus eu nisl dignissim, ac aliquet est lobortis.",
    price: 27.99,
    image: "./products/CubeSpeaker.jpeg",
    category: "Beauty",
    rating: 4.6,
    reviews: 12,
    discountedPrice: 40,
    offer: 0,
    earlyPrimeDeal: true,
    linkTitle: "View Product",
    link: "/product20",
    totalPurchase: 1234,
    trending: false,
  },
  
  {
    id: "22",
    name: "Renpho",
    description:
      "Proin accumsan lacus eu nisl dignissim, ac aliquet est lobortis.",
    price: 27.99,
    image: "./products/Renpho.jpeg",
    category: "Personal Care",
    rating: 4.6,
    reviews: 12,
    discountedPrice: 40,
    offer: 0,
    earlyPrimeDeal: true,
    linkTitle: "View Product",
    link: "/product20",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "23",
    name: "Echo Show",
    description:
      "Proin accumsan lacus eu nisl dignissim, ac aliquet est lobortis.",
    price: 27.99,
    image: "./products/EchoShow.jpeg",
    category: "Electronics",
    rating: 4.6,
    reviews: 12,
    discountedPrice: 40,
    offer: 0,
    freePrimeDeal: true,
    linkTitle: "View Product",
    link: "/product20",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "24",
    name: "Coach Shopping Bag",
    description:
      "Proin accumsan lacus eu nisl dignissim, ac aliquet est lobortis.",
    price: 27.99,
    image: "./products/ShoppingBag.jpeg",
    category: "Beauty",
    rating: 4.6,
    reviews: 12,
    discountedPrice: 40,
    offer: 0,
    freePrimeDeal: true,
    linkTitle: "View Product",
    link: "/product20",
    totalPurchase: 1234,
    trending: false,
  },
  {
    id: "25",
    name: "LG TV UR850",
    description:
      "Proin accumsan lacus eu nisl dignissim, ac aliquet est lobortis.",
    price: 27.99,
    image: "./products/LGTv.jpeg",
    category: "Electronics",
    rating: 4.6,
    reviews: 12,
    discountedPrice: 40,
    offer: 0,
    freePrimeDeal: true,
    linkTitle: "View Product",
    link: "/product20",
    totalPurchase: 1234,
    trending: false,
  },
];
export default ProductList;
